language: java

sudo: false

cache:
  directories:
    - '$HOME/.gradle'
    - '$HOME/.m2'
    - '$HOME/build'
    - '$HOME/helloservice/build'
    - '$HOME/timeservice/build'

notifications:
  email:
    recipients:
      - marcus@fihlon.ch
    on_success: always
    on_failure: always

services:
  - docker

after_success:
  - ./deploy
