= Kotlin EE
ifdef::env-github[:outfilesuffix: .adoc]

image:https://travis-ci.org/McPringle/kotlin-ee.svg?branch=master["Build Status", link="https://travis-ci.org/McPringle/kotlin-ee"]
image:https://img.shields.io/badge/gitmoji-%20😜%20😍-FFDD67.svg["gitmoji", link="https://gitmoji.carloscuesta.me"]

*This repository contains the source code of my live demo which is a part of my https://www.fihlon.ch/talks/abstracts/kotlin-ee/[Kotlin EE: Boost Your Productivity] talk.*

== Build

We use https://gradle.org/[Gradle] to build the two services. You can start the multi project build with just one command in the root folder:

```bash
./gradlew assemble
```

== Docker

To create the https://www.docker.org/[Docker] images for the two services, you have to run the following two commands:

```
docker build -t test/timeservice timeservice
docker build -t test/helloservice helloservice
```

If you want to push these images to the https://hub.docker.com/[Docker Hub] registry, you can replace the `test` prefix with your own https://hub.docker.com/[Docker Hub] user or organization name.

== Copyright and Licensing

Copyright (C) 2018 Marcus Fihlon

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

See the <<LICENSE#,LICENSE>> file for details.
